server.port: 9966
spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
spring.h2.console.enabled: true
spring:
  jpa:
    show-sql: true

org.springframework.logging:
  level: debug

#secret
com.eagulyi:
  facebook-api-url: graph.facebook.com
  facebook-api-version: v2.9
  appId:
  appSecret:
  security.jwt.tokenSigningKey:
  security.jwt:
    tokenExpirationTime: 30 # Number of days
    refreshTokenExpTime: 60 # Days
    tokenIssuer: http://eagulyi.com
    corsAllowedOrigin: http://localhost:4300

spring.datasource:
  url: "jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  username: sa
  password:
  driver-class-name: org.h2.Driver
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect